# Generated by Django 4.0.2 on 2022-02-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of the Student')),
                ('age', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=120)),
            ],
        ),
    ]
